# Numpy

### 2D array

In [7]:
import numpy as np
list1=[[10,20,30],[50,60,70]]
print(list1)
a=np.array([[10,20,30],[50,60,70]])
print(a)

[[10, 20, 30], [50, 60, 70]]
[[10 20 30]
 [50 60 70]]


In [2]:
import numpy as np
l=[[5,4,3],[8,7,6]]
a=np.array([[5,4,3],[8,7,6]])
print(a)

[[5 4 3]
 [8 7 6]]


### 1D Array

In [8]:
ar1=np.array([[10,20,30,50,60,70]])
print(ar1)

[[10 20 30 50 60 70]]


In [9]:
ar1

array([[10, 20, 30, 50, 60, 70]])

### array with different no.of elements

In [10]:
import numpy as np
l1=[[15,25,35],[45,55,65]]
print(l1)
a=np.array([[15,25,35],[45,55,65]])
print(a)
print(type(a))
print(type(l1))
print(a)

[[15, 25, 35], [45, 55, 65]]
[[15 25 35]
 [45 55 65]]
<class 'numpy.ndarray'>
<class 'list'>
[[15 25 35]
 [45 55 65]]


In [11]:
l1=[10,20,30,40,'g']
import numpy as np
arr=np.array(l1)
print(l1)
print(arr)

[10, 20, 30, 40, 'g']
['10' '20' '30' '40' 'g']


### string all elements converted to string

In [12]:
l1.append('x')
import numpy as np
arr=np.array(l1)
print(type(arr))
print(type(l1))
print(arr)

<class 'numpy.ndarray'>
<class 'list'>
['10' '20' '30' '40' 'g' 'x']


### with tuple

In [13]:
tup1=(10,20,30,40,'x','y')
import numpy as np
arr=np.array(tup1)
print(type(arr))
print(type(tup1))
print(tup1)
print(arr)


<class 'numpy.ndarray'>
<class 'tuple'>
(10, 20, 30, 40, 'x', 'y')
['10' '20' '30' '40' 'x' 'y']


### changes in the sub list won't impact main list

In [14]:
l1=[10,20,30,40,50,60,70,80]
l2=l1[:3]
print(l2)
l2[1]=400
print(l2)
print(l1)

[10, 20, 30]
[10, 400, 30]
[10, 20, 30, 40, 50, 60, 70, 80]


### if we update sliced array ,parent array also gets impacted

In [15]:
arr1=np.array(l1)
print(arr1)
arr2=arr1[:3]
print(arr2)
arr2[0]=700
print(arr1)
print(arr2)

[10 20 30 40 50 60 70 80]
[10 20 30]
[700  20  30  40  50  60  70  80]
[700  20  30]


### but in copy parent array won't impacted


In [16]:
print(arr1)
arr2=(arr1[0:3]).copy()
print(arr2)
arr2[1]=300
print(arr1)
print(arr2)

[700  20  30  40  50  60  70  80]
[700  20  30]
[700  20  30  40  50  60  70  80]
[700 300  30]


### matrix

In [17]:
import numpy as np
a=np.arange(9)
a=a.reshape((3,3))
print(a)
print(a[1][1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
4


In [18]:
b=np.zeros((4,4))
print(b)
b

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
b=np.ones((3,5))
print(b)
b

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### F for columns,c for rows

In [20]:
m1=np.arange(0,30)
m2=np.reshape(m1,(6,5),'F')
print(m1)
print(m2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


### create three list matrix  and transpose

In [21]:
l1=[10,20,30,40]
l2=[11,22,33,44]
l3=[12,22,32,42]
mat1=np.array([l1,l2,l3])
print(mat1)
print(mat1.T)


[[10 20 30 40]
 [11 22 33 44]
 [12 22 32 42]]
[[10 11 12]
 [20 22 22]
 [30 33 32]
 [40 44 42]]


### mat division

In [22]:
import numpy as np
l1=[100,110,120,130]
l2=[200,210,220,230]
l3=[300,310,320,330]
m1=np.array([l1,l2,l3])
l6=[10,11,12,13]
l7=[20,21,22,23]
l8=[30,31,32,33]
m2=np.array([l6,l7,l8])
m3=m1/m2
print(m1)
print(m2)
print(m3)
print(m2.ravel())

[[100 110 120 130]
 [200 210 220 230]
 [300 310 320 330]]
[[10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
[10 11 12 13 20 21 22 23 30 31 32 33]


In [23]:
a=np.arange(30)
b=a.reshape(2,5,3)
print(b)
n1=b.reshape(30,)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


### linear spaced vector

In [24]:
vector=np.linspace(0,30,11)
print(vector)

[ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30.]


### slicing

In [25]:
import numpy as np
arr=np.arange(100)
print(arr[10:],'\n')
print(arr[:20],'\n')
print(arr[10:20],'\n')
print(arr[10:50:5])
print(arr[::10])


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

[10 11 12 13 14 15 16 17 18 19] 

[10 15 20 25 30 35 40 45]
[ 0 10 20 30 40 50 60 70 80 90]


In [26]:
import numpy as np
arr=np.arange(20)
print(arr)
arr_slice=slice(1,10,2)
print(arr_slice)
print(arr[arr_slice])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
slice(1, 10, 2)
[1 3 5 7 9]


### extract 2*2  array from 3*3

In [27]:
import numpy as np
arr=np.arange(9)
print(arr)
arr=arr.reshape(3,3)
print('\n')
print(arr)
print('\n')
arr1=arr[0:2,0:2]
print(arr1)

[0 1 2 3 4 5 6 7 8]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[0 1]
 [3 4]]


In [28]:
import numpy as np
arr1=np.arange(9)
arr1=arr1.reshape(3,3)
print(arr1)
print('\n')
arr2=arr1[1:3,1:3]
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[4 5]
 [7 8]]


# Pandas

In [29]:
import numpy as np
import pandas as pd

### create series

In [30]:
a=pd.Series([10,20,30])
a

0    10
1    20
2    30
dtype: int64

In [31]:
a=np.array([10,20,30])
a

array([10, 20, 30])

In [32]:
arr1=np.array([10,12,14,16,18,20])
arr1

array([10, 12, 14, 16, 18, 20])

In [33]:
series=pd.Series(arr1)
series

0    10
1    12
2    14
3    16
4    18
5    20
dtype: int32

In [34]:
print(series[2:5])

2    14
3    16
4    18
dtype: int32


In [35]:
print(series[:5])

0    10
1    12
2    14
3    16
4    18
dtype: int32


### update values in series

In [36]:
dict={'A':10,'B':5,'C':8,'D':4}
dict

{'A': 10, 'B': 5, 'C': 8, 'D': 4}

In [37]:
a=pd.Series(dict)
a

A    10
B     5
C     8
D     4
dtype: int64

In [38]:
a['B':'D']

B    5
C    8
D    4
dtype: int64

In [39]:
a['C']=34

In [40]:
a

A    10
B     5
C    34
D     4
dtype: int64

In [41]:
d={'a':3}

In [42]:
d

{'a': 3}

### dataframes

### dictionary list

In [43]:
l1=[{'name':'john','age':27},{'name':'jessy','age':25},{'name':'sam','age':30},{'name':'nick','age':23}]
df=pd.DataFrame(l1)
df

name  age
0   john   27
1  jessy   25
2    sam   30
3   nick   23

In [44]:
df['age']

0    27
1    25
2    30
3    23
Name: age, dtype: int64

In [45]:
l2=[{'name':['john','sam','eric'],'age':[34,24,31]}]
df=pd.DataFrame(l2)
print(df)

                name           age
0  [john, sam, eric]  [34, 24, 31]


### list with one dictionary

In [46]:
l2={'name':['john','sam','eric'],'age':[34,24,31]}
df=pd.DataFrame(l2)
df

name  age
0  john   34
1   sam   24
2  eric   31

### dataframe from dictionary

In [47]:
a={'a':pd.Series([10,11,12],index=['a','b','c']),'b':pd.Series([10,11,12,13],index=['a','b','c','d'])}
tab=pd.DataFrame(a)
tab

a   b
a  10.0  10
b  11.0  11
c  12.0  12
d   NaN  13

In [48]:
l1=[['ravi',30,50000],['anil',25,30000],['sri',28,40000]]
df4=pd.DataFrame(l1)
df4

0   1      2
0  ravi  30  50000
1  anil  25  30000
2   sri  28  40000

### dataframe NaN

In [49]:
l1=[['ravi',30,50000],['anil',25,30000],['sri','shetty',28,40000]]
df4=pd.DataFrame(l1)
df4

0       1      2        3
0  ravi      30  50000      NaN
1  anil      25  30000      NaN
2   sri  shetty     28  40000.0

In [50]:
l1=[{'name':'ravi','age':30},{'name':'anil','age':25},{'name':'sri','age':30,'lastname':'shetty'},{'name':'nick','age':23}]
df=pd.DataFrame(l1)
df

name  age lastname
0  ravi   30      NaN
1  anil   25      NaN
2   sri   30   shetty
3  nick   23      NaN

### Row index

In [51]:
l1=[{'name':'ravi','age':30},{'name':'anil','age':25},{'name':'sri','age':30,'lastname':'shetty'},{'name':'nick','age':23}]
df=pd.DataFrame(l1,index=['R1','R2','R3','R4'])
df

name  age lastname
R1  ravi   30      NaN
R2  anil   25      NaN
R3   sri   30   shetty
R4  nick   23      NaN

In [52]:
pd.Series([10,11,12],index = ['a','b','c'])

a    10
b    11
c    12
dtype: int64

In [53]:
d1={'one':pd.Series([10,11,12],index=['a','b','c']),'two':pd.Series([10,11,12,13],index=['a','b','c','d'])}
df=pd.DataFrame(d1)
df

one  two
a  10.0   10
b  11.0   11
c  12.0   12
d   NaN   13

### addition of new column to dataframe(column)

In [54]:
df3={'ID':[101,102,103,104,105],'name':['john','mercy','akash','kavin','lally'],'profit':[20,34,56,87,70]}
df=pd.DataFrame(df3)
df

ID   name  profit
0  101   john      20
1  102  mercy      34
2  103  akash      56
3  104  kavin      87
4  105  lally      70

In [55]:
#if more column values it wont be added
df['salary']=pd.Series([10000,15000,20000,25000,30000],index=[0,1,2,3,4])
df

ID   name  profit  salary
0  101   john      20   10000
1  102  mercy      34   15000
2  103  akash      56   20000
3  104  kavin      87   25000
4  105  lally      70   30000

### print columns

In [56]:
print(df.columns[1])

name


In [57]:
print(df.columns[1:3])

Index(['name', 'profit'], dtype='object')


In [58]:
print(df[df.columns[1]])

0     john
1    mercy
2    akash
3    kavin
4    lally
Name: name, dtype: object


In [59]:
print(df[df.columns[0:2]])

    ID   name
0  101   john
1  102  mercy
2  103  akash
3  104  kavin
4  105  lally


In [60]:
df[df.columns[:2]]

ID   name
0  101   john
1  102  mercy
2  103  akash
3  104  kavin
4  105  lally

In [61]:
df[df.columns[1:]]

name  profit  salary
0   john      20   10000
1  mercy      34   15000
2  akash      56   20000
3  kavin      87   25000
4  lally      70   30000

### row naming

In [62]:
l2=[{'name':'josh','age':25},{'name':'ash','age':30},{'name':'ken','age':27},{'name':'nick','age':28,'lastname':'kim'}]
df2=pd.DataFrame(l2,index=['R1','R2','R3','R4'])
print(df2['name'])

R1    josh
R2     ash
R3     ken
R4    nick
Name: name, dtype: object


In [63]:
df2

name  age lastname
R1  josh   25      NaN
R2   ash   30      NaN
R3   ken   27      NaN
R4  nick   28      kim

In [64]:
print(df2[['name','age']])

    name  age
R1  josh   25
R2   ash   30
R3   ken   27
R4  nick   28


In [65]:
df2.columns[1]

'age'

In [66]:
df2.columns[1:3]

Index(['age', 'lastname'], dtype='object')

In [67]:
print(df2[df2.columns[1]])

R1    25
R2    30
R3    27
R4    28
Name: age, dtype: int64


In [68]:
print(df2[df2.columns[0:2]])

    name  age
R1  josh   25
R2   ash   30
R3   ken   27
R4  nick   28


In [69]:
print(df2[df2.columns[:2]])

    name  age
R1  josh   25
R2   ash   30
R3   ken   27
R4  nick   28


In [70]:
print(df2[df2.columns[1:]])

    age lastname
R1   25      NaN
R2   30      NaN
R3   27      NaN
R4   28      kim


### print rows

In [71]:
print(df2.index)

Index(['R1', 'R2', 'R3', 'R4'], dtype='object')


In [72]:
print(df2.iloc[1])

name        ash
age          30
lastname    NaN
Name: R2, dtype: object


In [73]:
print(df2.iloc[1:3])

   name  age lastname
R2  ash   30      NaN
R3  ken   27      NaN


In [74]:
print(df2.iloc[:3])

    name  age lastname
R1  josh   25      NaN
R2   ash   30      NaN
R3   ken   27      NaN


In [75]:
print(df2.iloc[1:])

    name  age lastname
R2   ash   30      NaN
R3   ken   27      NaN
R4  nick   28      kim


In [76]:
print(df2.index.values)

['R1' 'R2' 'R3' 'R4']


In [77]:
print(df2.index.values[1])

R2


In [78]:
print(df2.index.values[1:3])

['R2' 'R3']


### print column name

In [79]:
print(df2.loc['R1'])

name        josh
age           25
lastname     NaN
Name: R1, dtype: object


In [80]:
print(df2.loc['R2':])

    name  age lastname
R2   ash   30      NaN
R3   ken   27      NaN
R4  nick   28      kim


In [81]:
print(df2.loc[:'R3'])

    name  age lastname
R1  josh   25      NaN
R2   ash   30      NaN
R3   ken   27      NaN


### print rows and columns

In [82]:
df2.iloc[1:2,0:1]

name
R2  ash

### addition of rows

In [83]:
import numpy as np
import pandas as pd
d5={'name':['aish','priya','ren','thyme'],'maths':[87,99,92,75],'science':[74,90,91,86]}
df1=pd.DataFrame(d5)
display(df1)
d5={'name':['georia','amy'],'maths':[89,96],'science':[89,98]}
df2=pd.DataFrame(d5)
display(df2)
df3=pd.concat([df1,df2],ignore_index=True)
df3.reset_index()
display(df3)

name  maths  science
0   aish     87       74
1  priya     99       90
2    ren     92       91
3  thyme     75       86

name  maths  science
0  georia     89       89
1     amy     96       98

name  maths  science
0    aish     87       74
1   priya     99       90
2     ren     92       91
3   thyme     75       86
4  georia     89       89
5     amy     96       98

### drop rows

In [84]:
df3=df3.drop(0)
df3

name  maths  science
1   priya     99       90
2     ren     92       91
3   thyme     75       86
4  georia     89       89
5     amy     96       98

In [85]:
df3.reset_index()
df3

name  maths  science
1   priya     99       90
2     ren     92       91
3   thyme     75       86
4  georia     89       89
5     amy     96       98

### del a column

In [86]:
del(df1['science'])
print(df1)

    name  maths
0   aish     87
1  priya     99
2    ren     92
3  thyme     75


### pop is to assign some value

In [87]:
x=df2.pop('maths')
print(df2)
print(x)

     name  science
0  georia       89
1     amy       98
0    89
1    96
Name: maths, dtype: int64


### update values in dataframe

In [88]:
l2=[{'name':'john','age':28},{'name':'den','age':24},{'name':'ren','age':26},{'name':'jim','age':27}]
df=pd.DataFrame(l2)
df

name  age
0  john   28
1   den   24
2   ren   26
3   jim   27

In [89]:
df.iloc[0:1,0:1]='jack'
df

name  age
0  jack   28
1   den   24
2   ren   26
3   jim   27

### update multiple rows and columns

In [90]:
df.iloc[0:3,0:2]=['zen',24]
df

name  age
0  zen   24
1  zen   24
2  zen   24
3  jim   27

### joins

### create table from dictionary

In [91]:
std_data={'std_id':['AAA-123-2211','BBB-543-8765','CCC-876-9087','DDD-876-9876'],'first_name':['swathi','priya','aishu','namm'],'last_name':['kurra','gorre','chou','tiwari']}
std=pd.DataFrame(std_data,columns=['std_id','first_name','last_name'])
std

std_id first_name last_name
0  AAA-123-2211     swathi     kurra
1  BBB-543-8765      priya     gorre
2  CCC-876-9087      aishu      chou
3  DDD-876-9876       namm    tiwari

In [92]:
std_course={'std_id':['AAA-123-2211','BBB-543-8765','CCC-876-8765','DDD-876-9876'],'course':['ML','DS','R','PYTHON'],'duration':[3,4,5,6]}
course=pd.DataFrame(std_course)
course

std_id  course  duration
0  AAA-123-2211      ML         3
1  BBB-543-8765      DS         4
2  CCC-876-8765       R         5
3  DDD-876-9876  PYTHON         6

### concat both files

In [93]:
print(pd.concat([std,course]))

         std_id first_name last_name  course  duration
0  AAA-123-2211     swathi     kurra     NaN       NaN
1  BBB-543-8765      priya     gorre     NaN       NaN
2  CCC-876-9087      aishu      chou     NaN       NaN
3  DDD-876-9876       namm    tiwari     NaN       NaN
0  AAA-123-2211        NaN       NaN      ML       3.0
1  BBB-543-8765        NaN       NaN      DS       4.0
2  CCC-876-8765        NaN       NaN       R       5.0
3  DDD-876-9876        NaN       NaN  PYTHON       6.0


### axis=0-union

In [94]:
print(pd.concat([std,course],axis=0))

         std_id first_name last_name  course  duration
0  AAA-123-2211     swathi     kurra     NaN       NaN
1  BBB-543-8765      priya     gorre     NaN       NaN
2  CCC-876-9087      aishu      chou     NaN       NaN
3  DDD-876-9876       namm    tiwari     NaN       NaN
0  AAA-123-2211        NaN       NaN      ML       3.0
1  BBB-543-8765        NaN       NaN      DS       4.0
2  CCC-876-8765        NaN       NaN       R       5.0
3  DDD-876-9876        NaN       NaN  PYTHON       6.0


### index join

In [95]:
print(pd.concat([std,course],axis=1))

         std_id first_name last_name        std_id  course  duration
0  AAA-123-2211     swathi     kurra  AAA-123-2211      ML         3
1  BBB-543-8765      priya     gorre  BBB-543-8765      DS         4
2  CCC-876-9087      aishu      chou  CCC-876-8765       R         5
3  DDD-876-9876       namm    tiwari  DDD-876-9876  PYTHON         6


### merge to join two tables

In [96]:
pd.merge(std,course,left_on='std_id',right_on='std_id',how='inner')

std_id first_name last_name  course  duration
0  AAA-123-2211     swathi     kurra      ML         3
1  BBB-543-8765      priya     gorre      DS         4
2  DDD-876-9876       namm    tiwari  PYTHON         6

### left outer

In [97]:
pd.merge(std,course,left_on='std_id',right_on='std_id',how='left')

std_id first_name last_name  course  duration
0  AAA-123-2211     swathi     kurra      ML       3.0
1  BBB-543-8765      priya     gorre      DS       4.0
2  CCC-876-9087      aishu      chou     NaN       NaN
3  DDD-876-9876       namm    tiwari  PYTHON       6.0

### full outer

In [98]:
pd.merge(std,course,left_on='std_id',right_on='std_id',how='outer')

std_id first_name last_name  course  duration
0  AAA-123-2211     swathi     kurra      ML       3.0
1  BBB-543-8765      priya     gorre      DS       4.0
2  CCC-876-9087      aishu      chou     NaN       NaN
3  DDD-876-9876       namm    tiwari  PYTHON       6.0
4  CCC-876-8765        NaN       NaN       R       5.0

### example for join 

In [99]:
left=pd.DataFrame({'id':[1,2,3,4,5],'name':['alex','amy','alen','alice','ayoung'],'std_id':['sub6','sub2','sub3','sub4','sub5']})
right=pd.DataFrame({'id':[1,2,3,4,5],'name':['billi','brian','bran','bryce','betty'],'std_id':['sub1','sub2','sub4','sub5','sub6']})
print(left)
print('\n')
print(right)

   id    name std_id
0   1    alex   sub6
1   2     amy   sub2
2   3    alen   sub3
3   4   alice   sub4
4   5  ayoung   sub5


   id   name std_id
0   1  billi   sub1
1   2  brian   sub2
2   3   bran   sub4
3   4  bryce   sub5
4   5  betty   sub6


### join with two columns

In [100]:
left=pd.DataFrame({'id':[1,2,3,4,5],'name':['alex','amy','alen','alice','ayoung'],'sub_id':['sub1','sub2','sub3','sub4','sub5']})
right=pd.DataFrame({'id':[1,2,3,4,5],'name':['billi','brian','bran','bryce','betty'],'sub_id':['sub1','sub2','sub3','sub5','sub4']})
print(pd.merge(left,right,on=['id','sub_id']))

   id name_x sub_id name_y
0   1   alex   sub1  billi
1   2    amy   sub2  brian
2   3   alen   sub3   bran


### left join 

In [101]:
left=pd.DataFrame({'id':[1,2,3,4,5],'name':['alex','amy','alen','alice','ayoung'],'sub_id':['sub6','sub2','sub3','sub4','sub5']})
right=pd.DataFrame({'id':[1,2,3,4,5],'name':['billi','brian','bran','bryce','betty'],'sub_id':['sub1','sub2','sub6','sub4','sub5']})
print(pd.merge(left,right,on=['id','sub_id'],how = 'left'))

   id  name_x sub_id name_y
0   1    alex   sub6    NaN
1   2     amy   sub2  brian
2   3    alen   sub3    NaN
3   4   alice   sub4  bryce
4   5  ayoung   sub5  betty


In [102]:
print (pd.merge(left,right,on=['id','sub_id'], how = 'right'))

   id  name_x sub_id name_y
0   1     NaN   sub1  billi
1   2     amy   sub2  brian
2   3     NaN   sub6   bran
3   4   alice   sub4  bryce
4   5  ayoung   sub5  betty


In [103]:
print (pd.merge(left,right,on=['id','sub_id'], how = 'outer'))

   id  name_x sub_id name_y
0   1    alex   sub6    NaN
1   2     amy   sub2  brian
2   3    alen   sub3    NaN
3   4   alice   sub4  bryce
4   5  ayoung   sub5  betty
5   1     NaN   sub1  billi
6   3     NaN   sub6   bran


### import libraries

In [104]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [105]:
right

id   name sub_id
0   1  billi   sub1
1   2  brian   sub2
2   3   bran   sub6
3   4  bryce   sub4
4   5  betty   sub5

In [106]:
pd.read_csv('C:\\Users\\AISHWARYA\\Downloads\\prices.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\AISHWARYA\\Downloads\\prices.csv'

In [ ]:
import os
os.getcwd()
#cwdd=current working directory

In [ ]:
os.chdir('C:\\Users\\AISHWARYA\\Downloads\\')

In [ ]:
os.getcwd()

In [ ]:
stats=pd.read_csv('prices.csv')
stats

In [ ]:
tips=pd.read_csv('tips.csv')
tips

In [ ]:
stats.head()

In [ ]:
stats.tail()

In [ ]:
stats.head(10)

In [ ]:
print(len(stats))

In [ ]:
stats.shape

In [ ]:
len(stats.columns)

In [ ]:
#information about every column
stats.info()

In [ ]:
stats.describe()